"""Add wishlist item

Revision ID: 21b0ee7f2563
Revises: 
Create Date: 2020-12-31 07:42:44.424162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "21b0ee7f2563"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wishlist_item",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_wishlist_item_id"), "wishlist_item", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_wishlist_item_id"), table_name="wishlist_item")
    op.drop_table("wishlist_item")
    # ### end Alembic commands ###
