"""Link user to wishlistitem

Revision ID: dfac57b9426f
Revises: 6cd70f62a2ba
Create Date: 2021-01-31 08:07:12.759369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dfac57b9426f"
down_revision = "6cd70f62a2ba"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "wishlist_item", sa.Column("user_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(None, "wishlist_item", "user", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "wishlist_item", type_="foreignkey")
    op.drop_column("wishlist_item", "user_id")
    # ### end Alembic commands ###
