name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]
        poetry-version: [1.1.4]
        os: [ubuntu-18.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run image
        uses: abatilo/actions-poetry@v2.1.0
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: install project dependencies
        run: |
          poetry install

      - name: Lint black
        run: ./dev-scripts/check-black.sh

      - name: Lint flake 8
        run: ./dev-scripts/check-flake8.sh

      - name: Check Mypy
        run: ./dev-scripts/check-mypy.sh

# Commented out for now
#      - name: Check Pylint
#        run: ./dev-scripts/check-pylint.sh
      - name: Run tests
        run: ./dev-scripts/run-tests.sh
